### ISSUE TITLE
Output video has a weird pink filter

### ISSUE THREAD

**Issue by jnc-nj** [xx025/stable-video-diffusion-webui#7]
https://github.com/xx025/stable-video-diffusion-webui/assets/25879733/64dcf382-fe0a-4614-946c-d3a9c13af5aa

Not sure what's causing this, but it would be greatly appreciated if any advice could be given as to how to fix this.

**Comment by xx025** [comment]
this maybe acuse for `moviepy`

you can check this code 

https://github.com/xx025/stable-video-diffusion-webui/blob/41ce3581eb7b24faf2581deabdc694481002fe84/modules/img_tool.py#L115-L134



and  comments `shutil.rmtree(output_folder)` line, and go `output_folder` check every frames, is normal 


i select  `moviepy` because of opencv-python exist some encode problem, you can try continue use opencv-python method

only on `setting.py` file, set `creat_video_by_opencv =True`

https://github.com/xx025/stable-video-diffusion-webui/blob/41ce3581eb7b24faf2581deabdc694481002fe84/setting.py#L57-L60

**Comment by xx025** [comment]
apart, at ui page have a nsfw selct you can un-selct it, and try again
